language: node_js
node_js:
  - "10.14.1"
dist: trusty
sudo: required
branches:
  only:
  - master

addons:
  chrome: stable

cache:
  directories:
     - ./node_modules

install:
  - travis_wait npm install
  - travis_wait npm install -g @angular/cli@7.1.4
  - ng version
#  - chromedriver --version

#before_script:
#  - chromedriver-update 77.0.3865.40

script:
  - npm run test:headless
  - npm run build:docs
  - npm run build
#  - npm run e2e:headless
