name: Build, Compile, and Test Angular Components
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Setup
        run: npm ci

      - name: Run Static Tests
        run: |
          npm test -- --no-watch --watch=false --progress=false --no-progress --browsers=ChromeHeadlessCI
      - name: Ensure Documentation is Buildable
        run: |
          npm run build:docs
      - name: Ensure Angular Components Package Compiles
        run: |
          npm run build
      - name: Ensure Web Components Package Compiles
        run: |
          npm run build:web